# Generated by Django 5.2.8 on 2025-11-26 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('time', models.TimeField(verbose_name='Время бронирования')),
                ('duration', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Продолжительность (часы)')),
                ('guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Количество гостей')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('status', models.CharField(choices=[('pending', 'Ожидание подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-date', '-time'],
                'permissions': [('can_manage_all_reservations', 'Может управлять всеми бронированиями'), ('can_change_reservation_status', 'Может изменять статус бронирования')],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер столика')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Вместимость')),
                ('table_type', models.CharField(choices=[('standard', 'Стандартный'), ('booth', 'Бутылочный'), ('window', 'У окна'), ('vip', 'VIP')], default='standard', max_length=20, verbose_name='Тип столика')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'permissions': [('can_manage_tables', 'Может управлять столиками')],
            },
        ),
    ]
